name: Code coverage
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
      id: go

    - uses: actions/checkout@v4

    - name: Test
      run: go test -race -coverprofile=coverage.out -covermode=atomic
      
    - name: codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.out
